
configfile: "config/config.yaml"
singularity: "docker://mgatools/acmga:1.0"

rule anchor:
    # output:
    #     '../results/evelover.hal'
    params:
        xml = config["XML"],
        tree = config["Tree"],
        path = config["PATH"],
        fasta = ','.join(config["fasta"]),
        gff = ','.join(config["gff"]),
        unique=config["uniqueCds"],
        species=','.join(config["species"]),
        # ancestor=','.join(config['ancestor']),
        minimap2ForGff=config['minimap2ForGff'],
        minimap2Paramters=config['minimap2Paramters'],
        proaliParamters=config['proaliParamters'],
        genoaliParamters=config['genoaliParamters']

    shell:
        """
        echo {params.xml} {params.tree} {params.path} {params.fasta} 
        ./workflow/scripts/ACMGAPipeline.py {params.xml} {params.tree} {params.path} {params.fasta} {params.gff} {params.unique} {params.species}  "{params.minimap2ForGff}" "{params.minimap2Paramters}" "{params.proaliParamters}" "{params.genoaliParamters}" > data/result.sh 
        """






